# Generated by Django 4.1.3 on 2022-11-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Locations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("lat", models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ("lng", models.DecimalField(decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                "verbose_name": "Локация",
                "verbose_name_plural": "Локации",
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, null=True, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, null=True, verbose_name="Фамилия"),
                ),
                (
                    "username",
                    models.CharField(max_length=100, unique=True, verbose_name="Логин"),
                ),
                ("password", models.CharField(max_length=50, verbose_name="Пароль")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Пользователь"),
                            ("moderator", "Модератор"),
                            ("admin", "Администратор"),
                        ],
                        default="member",
                        max_length=10,
                    ),
                ),
                ("age", models.SmallIntegerField()),
                ("location_id", models.ManyToManyField(to="users.locations")),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "ordering": ["username"],
            },
        ),
    ]
